apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: blue-app
  template:
    metadata:
      labels:
        app: blue-app
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/nginx/html
      tolerations:
      - key: "example.com/blue"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      volumes:
      - name: config-volume
        configMap:
          name: blue-config
